/* Bloques de la Compañía — datos al 30/06/2026.
   Superficies brutas en km²; participación (WI) sobre el área total. */

export const BLOQUES = [
  {
    nombre: 'Loma Chivata Norte',
    provincia: 'Departamento Añelo, Neuquén',
    rol: 'Operado',
    etapa: 'Desarrollo',
    ventana: 'Petróleo negro',
    wi: '87,5%',
    superficie: '238 km²',
    superficieNeta: '208,3 km²',
    pozos: '96',
    produccion: '34.120',
    vencimiento: '2052',
    imagen: '/assets/img/bloque-loma-chivata-norte.jpg',
    alt: 'Pad de perforación en el bloque Loma Chivata Norte',
    texto:
      'Es el bloque fundacional de la Compañía y concentra el 43,5% de la producción. Cuenta con dieciocho pads en desarrollo y la infraestructura de tratamiento más importante del portafolio, la Batería Central II. El espaciamiento de pozos se estandarizó en 240 metros tras el análisis de interferencia realizado sobre el piloto de 2022.',
  },
  {
    nombre: 'Cañadón Mahuida',
    provincia: 'Departamento Añelo, Neuquén',
    rol: 'Operado',
    etapa: 'Desarrollo',
    ventana: 'Petróleo negro / volátil',
    wi: '100%',
    superficie: '141 km²',
    superficieNeta: '141,0 km²',
    pozos: '54',
    produccion: '18.640',
    vencimiento: '2049',
    imagen: '/assets/img/bloque-canadon-mahuida.jpg',
    alt: 'Instalaciones de superficie en Cañadón Mahuida',
    texto:
      'Único bloque con participación del 100%. La transición hacia la ventana de petróleo volátil en el sector norte elevó la relación gas-petróleo, lo que motivó la construcción de la planta de tratamiento de gas Mahuida, en servicio desde marzo de 2025.',
  },
  {
    nombre: 'Bajo del Cóndor',
    provincia: 'Departamento Pehuenches, Neuquén',
    rol: 'Operado',
    etapa: 'Desarrollo temprano',
    ventana: 'Petróleo negro',
    wi: '55%',
    superficie: '184 km²',
    superficieNeta: '101,2 km²',
    pozos: '31',
    produccion: '12.905',
    vencimiento: '2051',
    imagen: '/assets/img/bloque-bajo-del-condor.jpg',
    alt: 'Camino de acceso y locación en Bajo del Cóndor',
    texto:
      'Incorporado en septiembre de 2024. Los primeros veinte pozos horizontales superaron en un 12% la curva tipo estimada al momento de la adquisición. El acuerdo de operación conjunta prevé un programa mínimo de catorce pozos anuales hasta 2028.',
  },
  {
    nombre: 'Sierra Colorada Oeste',
    provincia: 'Departamento Añelo, Neuquén',
    rol: 'Operado',
    etapa: 'Desarrollo',
    ventana: 'Gas húmedo',
    wi: '70%',
    superficie: '176 km²',
    superficieNeta: '123,2 km²',
    pozos: '22',
    produccion: '9.870',
    vencimiento: '2054',
    imagen: '/assets/img/bloque-sierra-colorada-oeste.jpg',
    alt: 'Batería de separación en Sierra Colorada Oeste',
    texto:
      'Es el único bloque del portafolio orientado a gas. Su producción se evacúa por el gasoducto de vinculación de 28 kilómetros habilitado en 2025 y está comprometida en contratos de abastecimiento industrial de mediano plazo.',
  },
  {
    nombre: 'Puesto Aguada Sur',
    provincia: 'Departamento Pehuenches, Neuquén',
    rol: 'No operado',
    etapa: 'Evaluación exploratoria',
    ventana: 'En evaluación',
    wi: '22,5%',
    superficie: '492 km²',
    superficieNeta: '110,7 km²',
    pozos: '38',
    produccion: '2.877',
    vencimiento: '2047',
    imagen: '/assets/img/bloque-puesto-aguada-sur.jpg',
    texto:
      'Participación minoritaria en un bloque operado por un tercero, con producción convencional remanente y un programa exploratorio no convencional en curso. Durante 2025 se adquirieron 214 km² de sísmica 3D y está previsto un pozo exploratorio para el primer trimestre de 2027.',
  },
];
